

training:
  resume_path: null
  lr: 0.0001
  epochs: 50
  patience: 10
  batch_size: 16

  alphas: [1.0, 1.0, 5.0, 1.0, 1.0, 1.0, 0.2] # [leaf, root, stem, flower, fruit, seed, FOND]

  dataset: 
    data_dir: "data/thorns"
    transforms: ["random_crop", "random_hflip", "random_grayscale", "color_jitter", "gaussian_blur", "random_affine", "random_erase"] # ["random_crop", "random_hflip", "color_jitter", "random_erase"]
    use_yolo_weights: True
    train_split: 0.8
    n_samples: 100 # 'null' for all
    num_workers: 0
    precompute: True # precompute all expensive deterministic io tasks
    precompute_workers: 4
    store_cache: True # to store precomputed data on disk and use it if exists

    # when not using yolo weights
    weighted_patches: True
    weight_function: "linear"

    # when using yolo weights
    num_patches: 16
    patch_quotas: {0: 4, 1: 0, 2: 10, 3: 2, 4: 0, 5: 0, 6: 0}  # [0:leaf, 1:root, 2:stem, 3:flower, 4:fruit, 5:seed, 6:FOND]
    

  model:
    model_name: "dual_crossvit_yolo"
    crossvit: "crossvit_15_224"
    drop_rate: 0.1