

training:
  resume_path: null # path to previous run, "null" for new run
  lr: 0.0007
  lr_factors: {0: 1.0, 1: 0.5, 2: 0.3, 3: 0.1, 4: 0.05} # multiplying factor of LR for 0: heads, 1: norm, 2: blocks, 3: cls tok + pos embed, 4: patch embed
  epochs: 50
  patience: 8
  batch_size: 32
  freeze: True
  unfreeze_schedule: {0: 0, 1: 5, 2: 8, 3: 20, 4: 20} # 0: heads, 1: norm, 2: blocks, 3: cls tok + pos embed, 4: patch embed (ALL)

  alphas: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1] # [leaf, root, stem, flower, fruit, seed, FOND]

  model:
    model_name: "dual_crossvit_yolo" # all models in 'model/model_loaders.py' > DUALCROSSVIT_MAP
    crossvit: "crossvit_15_224" # all crossvit in 'model/crossvit_kwargs.py' > CROSSVIT_KWARGS_MAP
    drop_rate: 0.0


  dataset: 
    # data
    data_dir: "data/thorns"
    train_split: 0.8
    n_samples: null # debug, 'null' for all

    # model input
    branch_small: "yolo_patches" # "yolo_patches", "original", "segmented"
    branch_large: "orign" # "original", "segmented"
    branch_large_weight: "yolo_masks" # "yolo_masks", "ratio", null

    # training transforms
    transforms: ["random_affine", 
                 "random_hflip", 
                 "random_grayscale", 
                 "color_jitter", 
                 "random_erase"] # all transforms in 'dataset/dual_input_dataset.py' > TransformType

    # when using ratio weights
    ratio_weight_function: "parabole" # function applied to plant ratio to define weight of patch 
    ratio_patch_size: 16 # size of square patch to compute ratio from

    # when using yolo weights
    yolo_patch_count: 8 # total number of patches yolov7_ag
    yolo_patch_quotas: {0: 2, 1: 0, 2: 6, 3: 0, 4: 0, 5: 0, 6: 0}  # number of patches per classes yolov7_ag [0:leaf, 1:root, 2:stem, 3:flower, 4:fruit, 5:seed, 6:FOND]
    
    # speed optimizations
    num_workers: 0 # dataloader number of workers (recommended 0 if precomputed)
    precompute: True # precompute all expensive deterministic io tasks (/!\ includes selected yolo patches)
    use_cache: True # whether to use saved precomputed data if it exists
    store_cache: True # to store precomputed data on disk